trailingComma: "es5"
semi: true
singleQuote: false
arrowParens: always
bracketSpacing: true
quoteProps: as-needed
htmlWhitespaceSensitivity: ignore
plugins:
    - "@ianvs/prettier-plugin-sort-imports"
importOrderParserPlugins:
    - "typescript"
    - "classProperties"
    - "decorators"
importOrder:
    - "^@angular(/.*)?$"
    - ""
    - "^primeng(/.*)?$"
    - ""
    - <THIRD_PARTY_MODULES>
    - ""
    - "^@app(/.*)?$"
    - ""
    - "^(\\.).*$"
importOrderTypeScriptVersion: 4.7.4
